### ISSUE TITLE
Unconverted Contracts

### ISSUE THREAD

**Issue by ryanc55** [nepphhh/RP-0#12]
In contracts/milestones, docking.cfg, orbital recovery.cfg, and suborbital return.cfg have not been converted.

**Comment by nepphhh** [comment]
orbital recovery.cfg is done

**Comment by ryanc55** [comment]
Manned orbit contracts (Rendezvous, Orbital flight, etc.)  unconverted.

**Comment by nepphhh** [comment]
manned orbit contracts have been converted, stations, bases, and GPS remain

**Comment by nepphhh** [comment]
GPS are done

**Comment by nepphhh** [comment]
Done.
