### ISSUE TITLE
Exponent on geostationary weather satellite is overly large

### ISSUE THREAD

**Issue by SillySMS** [nepphhh/RP-0#16]
Currently, the payout for third-level weather satellites is dependent on payload to the 1.25'th power. This makes large GEO weather satellites pay out thousands of reputation if you use the RP-1 window to increase payload. I would suggest a power of 0.95 to 1.0.

https://github.com/nepphhh/RP-0/blob/NephsQuarterlyBudgets/GameData/RP-0/Contracts/SatelliteRepeat/WeatherSat3Geostationary.cfg
Line 35

The end-level commsat appears to not use a power function, while SSO weathersats don't appear to use the RP-1 slider, so far as I can tell.

**Comment by nepphhh** [comment]
No longer relevant in NewSats
